language: python


env:
  - PYTHON=2.7 DEPS=latest BACKEND=agg DOCTESTS=true
  - PYTHON=2.7 DEPS=pinned BACKEND=agg DOCTESTS=false
  - PYTHON=2.7 DEPS=latest BACKEND=qtagg DOCTESTS=true
  - PYTHON=3.5 DEPS=latest BACKEND=agg DOCTESTS=true
  - PYTHON=3.6 DEPS=latest BACKEND=agg DOCTESTS=true
  - PYTHON=3.6 DEPS=latest BACKEND=qtagg DOCTESTS=true
  - PYTHON=3.6 DEPS=minimal BACKEND=agg DOCTESTS=false


before_install:
  - sudo apt-get update -yq
  - sudo sh testing/getmsfonts.sh
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a


install:
  - conda create -n testenv pip python=$PYTHON
  - source activate testenv
  - cat testing/deps_${DEPS}.txt testing/utils.txt > deps.txt
  - conda install --file deps.txt
  - pip install .


before_script:
  - cp testing/matplotlibrc_${BACKEND} matplotlibrc
  - if [ $BACKEND == "qtagg" ]; then
    export DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3;
    fi


script:
  - make lint
  - if [ $DOCTESTS == 'true' ];
    then make coverage;
    else make unittests;
    fi


after_success:
    - pip install codecov
    - codecov
