name: CI

on:
  push:
    branches: [master, v0.*]
  pull_request:
    branches: master
  workflow_dispatch:

env:
  NB_KERNEL: python
  MPLBACKEND: Agg

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install seaborn
        run: |
          pip install --upgrade pip
          pip install .[stats,docs]

      - name: Install pandoc
        run: |
          sudo apt-get install pandoc

      - name: Build docs
        run: |
          make -C doc -j `nproc` notebooks
          make -C doc html


  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]
        target: [test]
        install: [full]
        deps: [latest]

        include:
          - python: "3.7"
            target: unittests
            install: full
            deps: pinned
          - python: "3.10"
            target: unittests
            install: light
            deps: latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - name: Install seaborn
        run: |
          pip install --upgrade pip wheel
          if [[ ${{matrix.install}} == 'full' ]]; then EXTRAS=',stats'; fi
          if [[ ${{matrix.deps }} == 'pinned' ]]; then DEPS='-r ci/deps_pinned.txt'; fi
          pip install .[dev$EXTRAS] $DEPS

      - name: Cache datastes
        run: python ci/cache_test_datasets.py

      - name: Run tests
        run: make ${{ matrix.target }}

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        if: ${{ success() }}

  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install tools
        run: pip install mypy flake8

      - name: Flake8
        run: make lint

      - name: Type checking
        run: make typecheck
